bytemarket/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('shop.urls', namespace='shop')),
    path('account/', include('account.urls', namespace='account')),
    path('cart/', include('cart.urls', namespace='cart')),
    path('order/', include('order.urls', namespace='order')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

cart/urls.py
from django.urls import path
from . import views

app_name = 'cart'

urlpatterns = [
    path('', views.index, name='cart'),
    path('update-cart/', views.update_cart, name='update_cart'),
    path('delete/', views.delete_item, name='delete_item'),
    path('clear/', views.clear_cart, name='clear_cart'),
]

order/urls.py
from django.urls import path
from . import views

app_name = 'order'

urlpatterns = [
    path('order-create/', views.order_create, name='order_create'),
    path('confirm-order/<int:order_id>/', views.confirm_order, name='confirm_order'),
    path('order-edit/<int:order_id>/', views.order_edit, name='order_edit'),
    path('order/detail/<order_id>/', views.order_detail, name='order_detail'),
    path('get/cities/', views.get_cities, name='get_cities'),
]

shop/urls.py
from django.urls import path
from . import views

app_name = 'shop'

urlpatterns = [
    path('', views.index, name='index'),
    path('products/', views.products_list, name='products_list_all'),
    path('products/category/<category_slug>/', views.products_list, name='products_list'),
    path('product/<id>/<slug>/', views.product_detail, name='product_detail'),
    path('products/search', views.product_search, name='product_search'),
    path('product/add/comment/<product_id>', views.add_comment, name='add_comment'),
    path('products/<portion>/', views.products_portion, name='products_portion'),
]

cart/models.py
from django.db import models

# Create your models here.

cart/views.py
from django.shortcuts import render
from django.http import JsonResponse
from django.views.decorators.http import require_POST
from django.contrib.humanize.templatetags.humanize import intcomma
from shop.models import Product
from .cart import Cart


def index(request):
    cart = Cart(request)
    context = {
        'cart': cart,
    }
    return render(request, 'cart/cart.html', context)


@require_POST
def update_cart(request):
    """
    This view is for managing the quantity of products in the card.
    
    Add a product to the cart if it does not exist in the cart 
    or increase the quantity of the product if the product already exist in the cart.
    
    Decrease the quantity of the product  in the cart.
    """
    product_id = request.POST.get('product_id')
    action = request.POST.get('action')
    product = Product.objects.get(id=product_id)
    cart = Cart(request)
    if action == "add":
        cart.add(product)
    elif action == "decrease":
        cart.decrease(product)
    data = {
        'cart_count': cart.count_item(),
        'cart_total_price': intcomma(cart.total_price()),
        'product_quantity': cart.cart.get(product_id)["quantity"],
        'item_total_price': intcomma(cart.cart.get(product_id)["quantity"] * cart.cart.get(product_id)["price"]),
        'post_price': intcomma(cart.post_price()),
        'final_price': intcomma(cart.final_total_price()),
    }
    return JsonResponse(data)


@require_POST
def delete_item(request):
    """ Delete the product from the cart."""
    product_id = request.POST.get('product_id')
    cart = Cart(request)
    cart.delete(product_id)
    data = {
        'cart_count': cart.count_item(),
        'cart_total_price': intcomma(cart.total_price()),
        'post_price': intcomma(cart.post_price()),
        'final_price': intcomma(cart.final_total_price()),
    }
    return JsonResponse(data)


@require_POST
def clear_cart(request):
    """ Delete all products from the cart."""
    cart = Cart(request)
    cart.clear()
    data = {
        'success': True,
    }
    return JsonResponse(data)

templates/cart/cart.html
{% extends 'parent/base.html' %}
{% load static %}
{% load humanize %}
{% block head %}
    <link rel="stylesheet" href="{% static 'style/cart.css' %}">
{% endblock %}
{% block title %} سبد خرید {% endblock %}
{% block body %}
    <div class="container">
        <div class="cart-wrapper">
            <div class="cart-products">
                <div class="cart-products-list">
                    {% if cart_count %}
                        {% for item in cart %}
                        <div class="cart-product" data-id="{{ item.product.id }}">
                            <div class="cart-product-image">
                                <a href="{% url 'shop:product_detail' item.product.id item.product.slug %}"><img src="{{ item.product.images.first.image_file.url }}" alt="product-image"></a>
                            </div>
                            <div class="cart-product-detail">
                                <a href="{% url 'shop:product_detail' item.product.id item.product.slug %}" class="cart-product-name">{{ item.product.name }}</a>
                                {% if item.product.off_percent %}
                                    <div class="cart-product-price">
                                        <p class="off">قیمت : {{ item.product.price | intcomma }} تومان</p>
                                        <p class="new-price">قیمت : {{ item.price | intcomma }} تومان</p>
                                    </div>
                                {% else %}
                                    <div class="cart-product-price">
                                        <p>قیمت : {{ item.product.price | intcomma }} تومان</p>
                                    </div>
                                {% endif %}
                                <div class="quantity-wrapper">
                                    <p class="quantity-{{ item.product.id }}">تعداد : {{ item.quantity }}</p>
                                    <div class="quantity-btns">
                                        <span class="increase-btn">
                                            <svg class="icon" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor">
                                                <path stroke-linecap="round" stroke-linejoin="round" d="M12 4.5v15m7.5-7.5h-15" />
                                            </svg>
                                        </span>
                                        <span class="decrease-btn">
                                            <svg class="icon" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor">
                                                <path stroke-linecap="round" stroke-linejoin="round" d="M5 12h14" />
                                            </svg>
                                        </span>
                                        <span class="delete-btn">
                                            <svg class="icon" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor">
                                                <path stroke-linecap="round" stroke-linejoin="round" d="m14.74 9-.346 9m-4.788 0L9.26 9m9.968-3.21c.342.052.682.107 1.022.166m-1.022-.165L18.16 19.673a2.25 2.25 0 0 1-2.244 2.077H8.084a2.25 2.25 0 0 1-2.244-2.077L4.772 5.79m14.456 0a48.108 48.108 0 0 0-3.478-.397m-12 .562c.34-.059.68-.114 1.022-.165m0 0a48.11 48.11 0 0 1 3.478-.397m7.5 0v-.916c0-1.18-.91-2.164-2.09-2.201a51.964 51.964 0 0 0-3.32 0c-1.18.037-2.09 1.022-2.09 2.201v.916m7.5 0a48.667 48.667 0 0 0-7.5 0" />
                                            </svg>
                                        </span>
                                    </div>
                                </div>
                            </div>
                        </div>
                        {% endfor %}
                    {% else %}
                        <p>سبد خرید شما خالی است.</p>
                    {% endif %}
                </div>
                <div class="cart-products-list-footer">
                    <button class="clear-cart">پاک کردن سبد خرید</button>
                    <a href="{% url 'shop:products_list_all' %}" class="return">بازگشت به لیست محصولات</a>
                </div>

            </div>
            <div class="price-detail">
                <div class="items">
                    {% for item in cart %}
                        <div class="item-{{ item.product.id }} item">
                            <p class="item-name">{{ item.product.name }}</p>
                            <div class="item-wrapper">
                                <p class="item-count-{{ item.product.id }}">تعداد : {{ item.quantity }}</p>
                                <p class="item-total-price-{{ item.product.id }}">قیمت : {{ item.total_price | intcomma }} تومان</p>
                            </div>
                        </div>
                    {% endfor %}
                </div>
                <p class="post-price">هزینه ارسال پست : {{ cart.post_price |intcomma }} تومان</p>
                <span class="seperate-line"></span>
                <p class="final-price">مبلغ کل : {{ cart.final_total_price | intcomma }} تومان</p>
                <a href="{% url 'order:order_create' %}" class="continue-buying">ادامه و تسویه حساب</a>
            </div>
        </div>
    </div>

<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.7.1/jquery.min.js" integrity="sha512-v2CJ7UaYy4JwqLDIrZUI/4hqeoQieOmAZNXBeQyjo21dadnwR+8ZaIJVT8EE2iyI61OV8e6M8PP2/4hpQINQ/g==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
<script>
    $(document).ready(function(){

        function updateTemplate(data, product_id){
            $('.quantity-'+product_id).text('تعداد : ' + data.product_quantity);
            $('.item-count-'+product_id).text('تعداد : ' + data.product_quantity);
            $('.item-total-price-'+product_id).text('قیمت : ' + data.item_total_price + ' تومان ');
            $('.final-price').text('مبلغ کل : ' + data.final_price + ' تومان ');
            $(".cart-total-price").text(data.cart_total_price + " تومان ");
            $(".cart-total-count").text(data.cart_count);
            $(".post-price").text(`هزینه ارسال پست : ${data.post_price} تومان`);
        }

        function update(action, product_id) {
            $.ajax({
                type: "POST",
                url: "{% url 'cart:update_cart' %}",
                data: {"csrfmiddlewaretoken": '{{ csrf_token }}',
                        "action": action,
                        "product_id": product_id,
                },
                success: function(data){
                    updateTemplate(data, product_id)
                }
            })
        }
        $(".increase-btn").click(function(){
            update("add", $(this).closest('.cart-product').data('id'))
        });
        $(".decrease-btn").click(function(){
            update("decrease", $(this).closest('.cart-product').data('id'))
        });
        $(".delete-btn").click(function(){
            let product_id = $(this).closest('.cart-product').data('id');
            let productElement = $(this).closest('.cart-product');
            $.ajax({
                type: "POST",
                url: '{% url "cart:delete_item" %}',
                data: {"csrfmiddlewaretoken": '{{ csrf_token }}', "product_id": product_id},
                success: function(data){
                    productElement.remove();
                    $('.item-' + product_id).remove();
                    $('.final-price').text('مبلغ کل : ' + data.final_price + ' تومان ');
                    $(".cart-total-price").text(data.cart_total_price + " تومان ");
                    $(".cart-total-count").text(data.cart_count);
                    $(".post-price").text(`هزینه ارسال پست : ${data.post_price} تومان`);
                }
            })
        });
        
        $(".clear-cart").click(function(){
            $.ajax({
                type: "POST",
                url: "{% url 'cart:clear_cart' %}",
                data: {'csrfmiddlewaretoken': '{{ csrf_token }}'},
                success: function(data){
                    $('.cart-total-price').text(0 + ' تومان ');
                    $('.cart-total-count').text(0);
                    $('.final-price').text('مبلغ کل : ' + 0 + ' تومان ');
                    $(".post-price").text(`هزینه ارسال پست : ${0} تومان`);
                }
            })
            $('.cart-products-list').empty();
            $('.cart-products-list').append('<p>سبد خرید شما خالی است.</p>');
            $('.items').empty();
        })
    });
</script>
{% endblock %}