account/urls.py
from django.urls import path
from . import views

app_name = 'account'

urlpatterns = [
    path('login/', views.verify_phone, name='verify_phone'),
    path('login/verify-code/', views.verify_code, name='verify_code'),
    path('login/resend-code/', views.resend_code, name='resend_code'),
    path('logout/', views.user_logout, name='logout'),
    path('my-account/', views.profile, name='profile'),
    path('user-info/edit/', views.user_info_edit, name='user_info_edit'),
]

bytemarket/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('shop.urls', namespace='shop')),
    path('account/', include('account.urls', namespace='account')),
    path('cart/', include('cart.urls', namespace='cart')),
    path('order/', include('order.urls', namespace='order')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

cart/urls.py
from django.urls import path
from . import views

app_name = 'cart'

urlpatterns = [
    path('', views.index, name='cart'),
    path('update-cart/', views.update_cart, name='update_cart'),
    path('delete/', views.delete_item, name='delete_item'),
    path('clear/', views.clear_cart, name='clear_cart'),
]

shop/urls.py
from django.urls import path
from . import views

app_name = 'shop'

urlpatterns = [
    path('', views.index, name='index'),
    path('products/', views.products_list, name='products_list_all'),
    path('products/category/<category_slug>/', views.products_list, name='products_list'),
    path('product/<id>/<slug>/', views.product_detail, name='product_detail'),
    path('products/search', views.product_search, name='product_search'),
    path('product/add/comment/<product_id>', views.add_comment, name='add_comment'),
    path('products/<portion>/', views.products_portion, name='products_portion'),
]

templates/partials/best_seller.html
{% load humanize %}
<div class="product-list">
    <div class="swiper best_seller_swiper">
        <div class="swiper-wrapper">
            {% for product in products %}
            <div class="swiper-slide">
                <div class="product">
                    <a href="{% url 'shop:product_detail' product.id product.slug %}">
                        <img class="product-image" src="{{ product.images.first.image_file.url }}" alt="product">
                    </a>
                    <a href="{% url 'shop:product_detail' product.id product.slug %}">
                        <p class="product-caption">{{ product.name }}</p>
                    </a>
                    {% if product.inventory %}
                    <div class="product-price">
                        {% if product.off_percent != 0 %}
                        <span class="price off"> {{ product.price | intcomma }} تومان</span>
                        <span class="price-off">{{ product.new_price | intcomma }} تومان</span>
                        {% else %}
                        <span class="price"> {{ product.price | intcomma }} تومان</span>
                        {% endif %}
                    </div>
                    {% else %}
                    <div class="product-price">
                        ناموجود
                    </div>
                    {% endif %}
                    {% if product.off_percent != 0 %}
                    <span class="off-percent">%{{ product.off_percent }}</span>
                    {% endif %}
                </div>
            </div>
            {% endfor %}
        </div>
    </div>

    <div class="previous-btn swiper-button-prev-best-seller">
        <svg viewBox="0 0 20 20" fill="currentColor">
            <path fill-rule="evenodd" d="M8.22 5.22a.75.75 0 0 1 1.06 0l4.25 4.25a.75.75 0 0 1 0 1.06l-4.25 4.25a.75.75 0 0 1-1.06-1.06L11.94 10 8.22 6.28a.75.75 0 0 1 0-1.06Z" clip-rule="evenodd" />
        </svg>
    </div>

    <div class="next-btn swiper-button-next-best-seller">
        <svg viewBox="0 0 20 20" fill="currentColor">
            <path fill-rule="evenodd" d="M11.78 5.22a.75.75 0 0 1 0 1.06L8.06 10l3.72 3.72a.75.75 0 1 1-1.06 1.06l-4.25-4.25a.75.75 0 0 1 0-1.06l4.25-4.25a.75.75 0 0 1 1.06 0Z" clip-rule="evenodd" />
        </svg>
    </div>
</div>

templates/partials/footer.html
{% load static %}
<footer>
    <div class="footer">
        <div class="contact">
            <div class="phone-wrapper">
                <p class="phone">تلفن : 021-77445812</p>
                <p class="email">ایمیل : example@gmail.com</p>
            </div>
            <div class="social-media">
                <p class="social-title">شبکه های اجتماعی</p>
                <div class="medias">
                    <a href="#" class="insta">
                        <img src="{% static 'images/icons/instagram-svgrepo-com.svg' %}" alt="icon">
                    </a>
                    <a href="#" class="tel">
                        <img src="{% static 'images/icons/telegram-svgrepo-com.svg' %}" alt="icon">
                    </a>
                    <a href="#" class="youtube">
                        <img src="{% static 'images/icons/youtube-svgrepo-com.svg' %}" alt="icon"> 
                    </a>
                    <a href="#" class="x">
                        <img src="{% static 'images/icons/twitter-color-svgrepo-com.svg' %}" alt="icon">
                    </a>
                </div>
            </div>
        </div>
    
        <div class="main-footer">
            <div class="quick-access">
                <p class="quick-title">دسترسی سریع</p>
                <ul>
                    <li><a href="#">تماس با ما</a></li>
                    <li><a href="#">در باره ما</a></li>
                    <li><a href="#">سوالات متداول</a></li>
                    <li><a href="#">بلاگ</a></li>
                </ul>
            </div>
            <div class="categories">
                <p class="categories-title">دسته بندی ها</p>
                <ul>
                    {% for category in header_categories %}
                    <li><a href="{% url 'shop:products_list' category.slug %}">{{ category.name }}</a></li>
                    {% endfor %}
                </ul>
            </div>
        </div>
        
        <div class="rights">
            <p>تمامی حقوق مادی و معنوی این سایت متعلق به <a href="https://github.com/Ho3ein02" target="_blank">Ho3ein02</a> می‌باشد.</p>
        </div>
    </div>
</footer>

templates/partials/header.html
{% load humanize %}

<!-- header for desktop -->
<header class="desktop-header">
    <div class="header-top">
        <!--   search bar     -->
        <form action="{% url 'shop:product_search' %}" class="search-container" method="get">
            <input class="search-input" type="text" placeholder="جستجوی محصولات" name="query">
            <a href="{% url 'shop:product_search' %}" class="search-button align-center">
                <svg class="search-icon icon" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor">
                    <path stroke-linecap="round" stroke-linejoin="round" d="m21 21-5.197-5.197m0 0A7.5 7.5 0 1 0 5.196 5.196a7.5 7.5 0 0 0 10.607 10.607Z" />
                </svg>
            </a>
        </form>

        <!--    login and cart desktop wrapper   -->
        <div class="profile-wrapper">
            {% if request.user.is_authenticated %}
                <a href="{% url 'account:profile' %}" class="profile align-center">
                    <svg class="icon" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor">
                        <path stroke-linecap="round" stroke-linejoin="round" d="M17.982 18.725A7.488 7.488 0 0 0 12 15.75a7.488 7.488 0 0 0-5.982 2.975m11.963 0a9 9 0 1 0-11.963 0m11.963 0A8.966 8.966 0 0 1 12 21a8.966 8.966 0 0 1-5.982-2.275M15 9.75a3 3 0 1 1-6 0 3 3 0 0 1 6 0Z" />
                    </svg>
                    <span class="profile-text">پروفایل</span>
                </a>
            {% else %}
                <a class="profile align-center" href="{% url 'account:verify_phone' %}">
                    <span class="profile-text">ورود / ثبت نام</span>
                </a>
            {% endif %}
            <a href="{% url 'cart:cart' %}" class="cart align-center">
                <svg class="icon" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor">
                    <path stroke-linecap="round" stroke-linejoin="round" d="M2.25 3h1.386c.51 0 .955.343 1.087.835l.383 1.437M7.5 14.25a3 3 0 0 0-3 3h15.75m-12.75-3h11.218c1.121-2.3 2.1-4.684 2.924-7.138a60.114 60.114 0 0 0-16.536-1.84M7.5 14.25 5.106 5.272M6 20.25a.75.75 0 1 1-1.5 0 .75.75 0 0 1 1.5 0Zm12.75 0a.75.75 0 1 1-1.5 0 .75.75 0 0 1 1.5 0Z" />
                </svg>
                <span class="cart-total-price">{{ cart_total_price | intcomma}} تومان</span>
                <span class="cart-total-count align-center">{{ cart_count }}</span>
            </a>
        </div>

    </div>
    <!--  menu  -->
    <nav class="navbar">
        <div class="category-dropdown">
            <div class="category-title">
                <svg class="icon" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor">
                    <path stroke-linecap="round" stroke-linejoin="round" d="M3.75 6.75h16.5M3.75 12h16.5m-16.5 5.25h16.5" />
                </svg>                  
                <p>دسته بندی ها</p>
                <ul class="category">
                    {% for category in header_categories %}
                    <li class="category-item"><a href="{% url 'shop:products_list' category.slug %}">{{ category.name }}</a></li>
                    {% endfor %}
                </ul>
            </div>
        </div>
        <ul class="nav-links">
            <li><a href="{% url 'shop:index' %}">صفحه اصلی</a></li>
            <li><a href="#">درباره ما</a></li>
            <li><a href="#">تماس با ما</a></li>
        </ul>
    </nav>
</header>

<!-- header for mobile -->
<header class="mobile-header">
    <!--    login and cart mobile  -->
    <div class="header-top">
        <a href="{% url 'cart:cart' %}" class="cart align-center">
            <svg class="icon" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor">
                <path stroke-linecap="round" stroke-linejoin="round" d="M2.25 3h1.386c.51 0 .955.343 1.087.835l.383 1.437M7.5 14.25a3 3 0 0 0-3 3h15.75m-12.75-3h11.218c1.121-2.3 2.1-4.684 2.924-7.138a60.114 60.114 0 0 0-16.536-1.84M7.5 14.25 5.106 5.272M6 20.25a.75.75 0 1 1-1.5 0 .75.75 0 0 1 1.5 0Zm12.75 0a.75.75 0 1 1-1.5 0 .75.75 0 0 1 1.5 0Z" />
            </svg>
            <span class="cart-total-price">{{ cart_total_price | intcomma}} تومان</span>
            <span class="cart-total-count align-center">{{ cart_count }}</span>
        </a>
        <div class="profile-wrapper-mobile">
            <form action="{% url 'shop:product_search' %}" class="search-container" method="get">
                <input class="search-input" type="text" placeholder="جستجوی محصولات" name="query">
                <a href="{% url 'shop:product_search' %}" class="search-button align-center">
                    <svg class="search-icon icon" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor">
                        <path stroke-linecap="round" stroke-linejoin="round" d="m21 21-5.197-5.197m0 0A7.5 7.5 0 1 0 5.196 5.196a7.5 7.5 0 0 0 10.607 10.607Z" />
                    </svg>
                </a>
            </form>
            <div class="menu-icon">
                <span class="menu-icon__line"></span>
            </div>
        </div>
    </div>

    <!-- mobile menu -->
    <div class="nav-menu">
        <ul class="mobile-menu">
            <li class="mobile-menu__item">
                <a href="{% url 'shop:index' %}" class="mobile-menu__link">صفحه اصلی</a>
            </li>
            <li class="mobile-menu__item">
                <a href="#" class="mobile-menu__link">درباره ما</a>
            </li>
            <li class="mobile-menu__item">
                <a href="#" class="mobile-menu__link">تماس با ما</a>
            </li>
        </ul>
        <div>
            <p class="category-mobile-title">دسته بندی ها</p>
            <ul class="category-mobile">
                {% for category in header_categories %}
                <li class="mobile-menu__item"><a href="{% url 'shop:products_list' category.slug %}" class="mobile-menu__link">{{ category.name }}</a></li>
                {% endfor %}
            </ul>
        </div>
        {% if request.user.is_authenticated %}
            <a href="{% url 'account:profile' %}" class="profile align-center">
                <svg class="icon" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor">
                    <path stroke-linecap="round" stroke-linejoin="round" d="M17.982 18.725A7.488 7.488 0 0 0 12 15.75a7.488 7.488 0 0 0-5.982 2.975m11.963 0a9 9 0 1 0-11.963 0m11.963 0A8.966 8.966 0 0 1 12 21a8.966 8.966 0 0 1-5.982-2.275M15 9.75a3 3 0 1 1-6 0 3 3 0 0 1 6 0Z" />
                </svg>
                <span class="profile-text">پروفایل</span>
            </a>
        {% else %}
            <a class="profile align-center" href="{% url 'account:verify_phone' %}">
                <span class="profile-text">ورود / ثبت نام</span>
            </a>
        {% endif %}
    </div>
</header>

templates/partials/latest_products.html
{% load humanize %}
<div class="product-list">
    <div class="swiper newest_swiper">
        <div class="swiper-wrapper">
            {% for product in products %}
            <div class="swiper-slide">
                <div class="product">
                    <a href="{% url 'shop:product_detail' product.id product.slug %}">
                        <img class="product-image" src="{{ product.images.first.image_file.url }}" alt="product">
                    </a>
                    <a href="{% url 'shop:product_detail' product.id product.slug %}">
                        <p class="product-caption">{{ product.name }}</p>
                    </a>
                    {% if product.inventory %}
                    <div class="product-price">
                        {% if product.off_percent != 0 %}
                        <span class="price off"> {{ product.price | intcomma }} تومان</span>
                        <span class="price-off">{{ product.new_price | intcomma }} تومان</span>
                        {% else %}
                        <span class="price"> {{ product.price | intcomma }} تومان</span>
                        {% endif %}
                    </div>
                    {% else %}
                    <div class="product-price">
                        ناموجود
                    </div>
                    {% endif %}
                    {% if product.off_percent != 0 %}
                    <span class="off-percent">%{{ product.off_percent }}</span>
                    {% endif %}
                </div>
            </div>
            {% endfor %}
        </div>
    </div>

    <div class="previous-btn swiper-button-prev-newest">
        <svg viewBox="0 0 20 20" fill="currentColor">
            <path fill-rule="evenodd" d="M8.22 5.22a.75.75 0 0 1 1.06 0l4.25 4.25a.75.75 0 0 1 0 1.06l-4.25 4.25a.75.75 0 0 1-1.06-1.06L11.94 10 8.22 6.28a.75.75 0 0 1 0-1.06Z" clip-rule="evenodd" />
        </svg>
    </div>

    <div class="next-btn swiper-button-next-newest">
        <svg viewBox="0 0 20 20" fill="currentColor">
            <path fill-rule="evenodd" d="M11.78 5.22a.75.75 0 0 1 0 1.06L8.06 10l3.72 3.72a.75.75 0 1 1-1.06 1.06l-4.25-4.25a.75.75 0 0 1 0-1.06l4.25-4.25a.75.75 0 0 1 1.06 0Z" clip-rule="evenodd" />
        </svg>
    </div>
</div>

templates/partials/pagination.html
{% load shop_tags %}
<div class="pagination">
    {% if products.has_previous %}
    <a href="?page={{ products.previous_page_number }}" class="pagination-prev-btn" onclick="paginationClickHandler(event)"> > </a>
    {% endif %}
    {% custom_get_elided_page_range products.paginator products.number as page_range %}
    {% for page_number in page_range %}
    <a href="?page={{ page_number }}" class="page-btn {% if products.number == page_number %} page-btn-active {% endif %}" onclick="paginationClickHandler(event)">{{ page_number }}</a>
    {% endfor %}
    {% if products.has_next %}
    <a href="?page={{ products.next_page_number }}" class="pagination-next-btn" onclick="paginationClickHandler(event)"> < </a>
    {% endif %}
</div>

templates/partials/suggestion_products.html
{% load humanize %}
<div class="product-list">
    <div class="swiper seggestion_swiper">
        <div class="swiper-wrapper">
            {% for product in products %}
            <div class="swiper-slide">
                <div class="product">
                <a href="{% url 'shop:product_detail' product.id product.slug %}">
                    <img class="product-image" src="{{ product.images.first.image_file.url }}" alt="product">
                </a>
                <a href="{% url 'shop:product_detail' product.id product.slug %}">
                    <p class="product-caption">{{ product.name }}</p>
                </a>
                <div class="product-price">
                    <span class="price off"> {{ product.price | intcomma }} تومان</span>
                    <span class="price-off">{{ product.new_price | intcomma }} تومان</span>
                </div>
                <span class="off-percent">%{{ product.off_percent }}</span>
                <div class="product-separator"></div>
            </div>
            </div>
            {% endfor %}
        </div>
      </div>
    <div class="previous-btn swiper-button-prev-custom">
        <svg viewBox="0 0 20 20" fill="currentColor">
            <path fill-rule="evenodd" d="M8.22 5.22a.75.75 0 0 1 1.06 0l4.25 4.25a.75.75 0 0 1 0 1.06l-4.25 4.25a.75.75 0 0 1-1.06-1.06L11.94 10 8.22 6.28a.75.75 0 0 1 0-1.06Z" clip-rule="evenodd" />
        </svg>
    </div>

    <div class="next-btn swiper-button-next-custom">
        <svg viewBox="0 0 20 20" fill="currentColor">
            <path fill-rule="evenodd" d="M11.78 5.22a.75.75 0 0 1 0 1.06L8.06 10l3.72 3.72a.75.75 0 1 1-1.06 1.06l-4.25-4.25a.75.75 0 0 1 0-1.06l4.25-4.25a.75.75 0 0 1 1.06 0Z" clip-rule="evenodd" />
        </svg>
    </div>
</div>