bytemarket/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('shop.urls', namespace='shop')),
    path('account/', include('account.urls', namespace='account')),
    path('cart/', include('cart.urls', namespace='cart')),
    path('order/', include('order.urls', namespace='order')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

cart/urls.py
from django.urls import path
from . import views

app_name = 'cart'

urlpatterns = [
    path('', views.index, name='cart'),
    path('update-cart/', views.update_cart, name='update_cart'),
    path('delete/', views.delete_item, name='delete_item'),
    path('clear/', views.clear_cart, name='clear_cart'),
]

shop/urls.py
from django.urls import path
from . import views

app_name = 'shop'

urlpatterns = [
    path('', views.index, name='index'),
    path('products/', views.products_list, name='products_list_all'),
    path('products/category/<category_slug>/', views.products_list, name='products_list'),
    path('product/<id>/<slug>/', views.product_detail, name='product_detail'),
    path('products/search', views.product_search, name='product_search'),
    path('product/add/comment/<product_id>', views.add_comment, name='add_comment'),
    path('products/<portion>/', views.products_portion, name='products_portion'),
]

shop/models.py
from django.db import models
from django.urls import reverse
from django_jalali.db import models as jmodels
from account.models import User


class Category(models.Model):
    name = models.CharField(max_length=255)
    slug = models.SlugField(max_length=255, unique=True)

    class Meta:
        ordering = ['name']
    
    def save(self, *args, **kwargs):
        self.slug = self.name.replace(' ', '-')
        super().save(*args, **kwargs)

    def __str__(self):
        return self.name


class Brand(models.Model):
    name = models.CharField(max_length=250)
    slug = models.SlugField(max_length=250)

    def save(self, *args, **kwargs):
        self.slug = self.name.lower().replace(' ', '-')
        super().save(*args, **kwargs)
        
    def __str__(self):
        return self.name


class Product(models.Model):
    category = models.ForeignKey(Category, on_delete=models.CASCADE, related_name='products')
    brand = models.ForeignKey(Brand, on_delete=models.CASCADE, related_name='products', null=True, blank=True)
    name = models.CharField(max_length=255)
    slug = models.SlugField(max_length=255)
    description = models.TextField()
    weight = models.PositiveIntegerField(default=0)
    price = models.PositiveIntegerField(default=0)
    off_percent = models.PositiveIntegerField(default=0)
    new_price = models.PositiveIntegerField(default=0)
    inventory = models.PositiveIntegerField(default=0)
    created = jmodels.jDateTimeField(auto_now_add=True)
    updated = jmodels.jDateTimeField(auto_now=True)

    class Meta:
        ordering = ['-created', '-inventory', 'price', 'off_percent', '-price']
        indexes = [
            models.Index(fields=('slug', 'id')),
            models.Index(fields=('name',)),
            models.Index(fields=('created',)),
        ]

    def save(self, *args, **kwargs):
        self.slug = self.name.lower().replace(' ', '-')
        super().save(*args, **kwargs)
    
    def get_absolute_url(self):
        return reverse('shop:product_detail', args=[self.id, self.slug])

    def __str__(self):
        return self.name


class ProductFeature(models.Model):
    name = models.CharField(max_length=255)
    value = models.CharField(max_length=255)
    product = models.ForeignKey(Product, on_delete=models.CASCADE, related_name="features")

    def __str__(self):
        return f"{self.name}: {self.value}"


class ProductImage(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE, related_name='images')
    image_file = models.ImageField(upload_to='product_images/%Y-%m-%d', max_length=255)
    title = models.CharField(max_length=255)
    created = jmodels.jDateTimeField(auto_now_add=True)

    def __str__(self):
        return self.title


class Comment(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='user_comments')
    product = models.ForeignKey(Product, on_delete=models.CASCADE, related_name='product_comments')
    parent = models.ForeignKey('self', on_delete=models.CASCADE, related_name='replies', null=True, blank=True)
    content = models.TextField()
    active = models.BooleanField(default=False)
    created = jmodels.jDateTimeField(auto_now_add=True)
    
    class Meta:
        ordering = ['-created']

    def __str__(self):
        return f"comment {self.id} by {self.user}"

shop/forms.py
from django import forms
from .models import Brand, Category


class ProductFilterForm(forms.Form):
    available = forms.BooleanField(required=False)
    max_price = forms.DecimalField(min_value=0, required=False)
    min_price = forms.DecimalField(min_value=0, required=False)

    # Field for checkbox
    brand = forms.ModelMultipleChoiceField(queryset=Brand.objects.all(),
                                           widget=forms.CheckboxSelectMultiple,
                                           required=False)

    # Field for checkbox
    category = forms.ModelMultipleChoiceField(queryset=Category.objects.all(),
                                              widget=forms.CheckboxSelectMultiple,
                                              required=False)


class SearchForm(forms.Form):
    query = forms.CharField(required=False)


class CommentForm(forms.Form):
    comment = forms.CharField(widget=forms.Textarea)
    parent = forms.CharField()

shop/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views.decorators.http import require_POST
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.http import JsonResponse
from django.db.models import Max, Sum
from django.contrib.postgres.search import TrigramSimilarity
from .models import *
from order.models import *
from .forms import *
from itertools import chain


def index(request):
    return render(request, 'shop/index.html')


def filter_products(request, products):
    """Returns the filtered and sorted products"""
    # Filter products
    filter_form = ProductFilterForm(request.GET)
    if filter_form.is_valid():
        available = filter_form.cleaned_data.get('available')
        max_price = filter_form.cleaned_data.get('max_price')
        min_price = filter_form.cleaned_data.get('min_price')
        brand = filter_form.cleaned_data.get('brand')
        category = filter_form.cleaned_data.get('category')
        if available:
            products = products.filter(inventory__gt=0)
        if min_price:
            products = products.filter(price__gt=min_price)
        if max_price:
            products = products.filter(price__lt=max_price)
        if brand:
            products = products.filter(brand__in=brand)
        if category:
            products = products.filter(category__in=category)
    
    # Sort products based on user selection
    
    ordering = request.GET.get('ordering')
    # In order for the unavailable part of the products to be at the end of the list and to sort the available part of the products, we must separate them
    available_inventory_products = products.filter(inventory__gt=0)  # Separate the available products section
    unavailable_inventory_products = products.filter(inventory=0)    # Separate the unavailable products section
    # Sort the available products section
    if ordering == 'newest':
        available_inventory_products = available_inventory_products.order_by('-created')
    elif ordering == 'price_asc':
        available_inventory_products = available_inventory_products.order_by('price')
    elif ordering == 'price_desc':
        available_inventory_products = available_inventory_products.order_by('-price')
    elif ordering == 'off_desc':
        available_inventory_products = available_inventory_products.order_by('-off_percent')
    
    products = list(chain(available_inventory_products, unavailable_inventory_products))  # Combination of available and unavailable parts
    
    return products


def product_detail(request, id, slug):
    product = get_object_or_404(Product, id=id, slug=slug)
    comments = Comment.objects.filter(product=product, active=True, parent=None)
    context = {
        'product': product,
        'comments': comments,
    }
    return render(request, 'shop/product_detail.html', context)


def products_list(request, category_slug=None):
    if category_slug:
        products = get_object_or_404(Category, slug=category_slug).products.all().order_by('-inventory')
    else:
        products = Product.objects.all()
    brands = Brand.objects.all()
    price_max = products.aggregate(Max('price', default=0))
    
    products = filter_products(request, products)
    
    # Product pagination
    paginator = Paginator(products, 12)
    page_number = request.GET.get('page', 1)
    try:
        products = paginator.page(page_number)
    except (EmptyPage, PageNotAnInteger):
        products = paginator.page(1)
    
    # Send the response as json if the request is ajax
    if request.headers.get('x-requested-with') == 'XMLHttpRequest':
        return render(request, 'shop/product_list_ajax.html', {'products': products})
    
    context = {
        'products': products,
        'brands': brands,
        'price_max': price_max['price__max'],
    }
    
    return render(request, 'shop/product_list.html', context)


def product_search(request):
    products = Product.objects.all()
    brands = Brand.objects.all()
    price_max = products.aggregate(Max('price', default=0))
    categories = Category.objects.all()

    query = ''
    
    # Find products that the user has searched for
    search_form = SearchForm(request.GET)
    if search_form.is_valid():
        query = search_form.cleaned_data['query']
        if query:
            trigram1 = products.annotate(similarity=TrigramSimilarity('name', query)).filter(similarity__gt=0.1)            # Search by name
            trigram2 = products.annotate(similarity=TrigramSimilarity('brand__name', query)).filter(similarity__gt=0.1)     # Search by brand
            trigram3 = products.annotate(similarity=TrigramSimilarity('category__name', query)).filter(similarity__gt=0.1)  # Search by category
            products = trigram1 | trigram2 | trigram3
    
    products = filter_products(request, products)
    
    # Product pagination
    paginator = Paginator(products, 12)
    page_number = request.GET.get('page', 1)
    try:
        products = paginator.page(page_number)
    except (EmptyPage, PageNotAnInteger):
        products = paginator.page(1)

    # Send the response as json if the request is ajax
    if request.headers.get('x-requested-with') == 'XMLHttpRequest':
        return render(request, 'shop/product_list_ajax.html', {'products': products})
    
    context = {
        'products': products,
        'brands': brands,
        'price_max': price_max['price__max'],
        'categories': categories,
        'query': query,
    }
    return render(request, 'shop/product_search.html', context)


@require_POST
def add_comment(request, product_id):
    user = request.user
    if user.is_authenticated:
        form = CommentForm(request.POST)
        if form.is_valid():
            cd = form.cleaned_data
            comment_text = cd['comment']
            parent_id = cd['parent']
            if parent_id == 'None':
                parent = None
            else:
                parent = get_object_or_404(Comment, id=parent_id)
            product = get_object_or_404(Product, id=product_id)
            Comment.objects.create(user=user, product=product, parent=parent, content=comment_text)
            data = {
                'success': True,
                'message': 'نظر شما با موفقیت ثبت شد.\nپس از بررسی توسط ادمین منتشر خواهد شد.',
            }
            return JsonResponse(data)
    else:
        data = {
            'success': False,
            'message': 'برای ثبت نظر لطفا ابتدا وارد شوید.'
        }
        return JsonResponse(data)


def products_portion(request, portion):
    if portion == 'suggestion':
        products = Product.objects.filter(off_percent__gt=0, inventory__gt=0).order_by('-off_percent')
    elif portion == 'best_seller':
        order_items = OrderItem.objects.filter(order__is_paid=True)
        products = Product.objects.filter(order_items__in=order_items).annotate(sell_count=Sum('order_items__quantity')).order_by('-sell_count')
    elif portion == 'newest':
        products = Product.objects.all().order_by('-created')
    brands = Brand.objects.all()
    price_max = products.aggregate(Max('price', default=0))
    
    products = filter_products(request, products)
    
    paginator = Paginator(products, 12)
    page_number = request.GET.get('page', 1)
    try:
        products = paginator.page(page_number)
    except (EmptyPage, PageNotAnInteger):
        products = paginator.page(1)

    if request.headers.get('x-requested-with') == 'XMLHttpRequest':
        return render(request, 'shop/product_list_ajax.html', {'products': products})
    
    context = {
        'products': products,
        'brands': brands,
        'price_max': price_max['price__max'],
    }
    return render(request, 'shop/product_list.html', context)

templates/shop/index.html
{% extends 'parent/base.html' %}
{% load static %}
{% load shop_tags %}
{% block title %}  بایت مارکت {% endblock %}
{% block head %}
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/swiper@11/swiper-bundle.min.css" />
{% endblock %}

{% block body %}
<main>
    <div class="container">
        <!-- banner section -->
        <section class="banner-section">
            <div class="swiper banner_swiper">
                <div class="swiper-wrapper">
                  <div class="swiper-slide">
                    <div class="banner">
                        <img src="{% static 'images/banners/banner1.png' %}" alt="laptop banner" class="banner_img">
                    </div>
                  </div>
                  <div class="swiper-slide">
                    <div class="banner">
                        <img src="{% static 'images/banners/banner2.png' %}" alt="laptop banner" class="banner_img">
                    </div>
                  </div>
                  <div class="swiper-slide">
                    <div class="banner">
                        <img src="{% static 'images/banners/banner3.png' %}" alt="laptop banner" class="banner_img">
                    </div>
                  </div>
                </div>
                <div class="swiper-button-next"></div>
                <div class="swiper-button-prev"></div>
              </div>
        </section>

        <!-- suggestion section -->
        <section class="suggestion-products">
            <div class="suggestion-header">
                <span class="separate-line"></span>
                <span class="suggestion-title">پیشنهاد شگفت انگیز</span>
                <span class="separate-line"></span>
                <a href="{% url 'shop:products_portion' 'suggestion' %}" class="show-all">مشاهده همه</a>
            </div>
            {% suggestion_products %}
        </section>

        <!-- best seller section -->
        <section class="main-section">
            <div class="section-header">
                <div class="title-wrapper">
                    <span class="right-line"></span>
                    <span class="section-title">پرفروش ترین ها</span>
                </div>
                <a href="{% url 'shop:products_portion' 'best_seller' %}" class="show-all">مشاهده همه</a>
            </div>
            {% best_seller_products %}
        </section>

        <!-- newest section -->
        <section class="main-section">
            <div class="section-header">
                <div class="title-wrapper">
                    <span class="right-line"></span>
                    <span class="section-title">جدیدترین محصولات</span>
                </div>
                <a href="{% url 'shop:products_portion' 'newest' %}" class="show-all">مشاهده همه</a>
            </div>
            {% latest_products %}
        </section>
    </div>
</main>
<div class="cover"></div>
<script type="module">
    import Swiper from 'https://cdn.jsdelivr.net/npm/swiper@11/swiper-bundle.min.mjs'

    var swiper = new Swiper(".banner_swiper", {
        spaceBetween: 30,
        centeredSlides: true,
        autoplay: {
            delay: 2500,
            disableOnInteraction: false,
        },
        pagination: {
            el: ".swiper-pagination",
            clickable: true,
        },
        navigation: {
            nextEl: ".swiper-button-next",
            prevEl: ".swiper-button-prev",
        },
    });
    var seggustion_swiper = new Swiper(".seggestion_swiper", {
        slidesPerView: 2,
        spaceBetween: 5,
        pagination: {
            el: ".swiper-pagination",
            clickable: true,
        },
        navigation: {
            nextEl: ".swiper-button-next-custom",
            prevEl: ".swiper-button-prev-custom",
        },
        breakpoints: {
            640: {
                slidesPerView: 3,
                spaceBetween: 5,
            },
            768: {
                slidesPerView: 3,
                spaceBetween: 30,
            },
            1024: {
                slidesPerView: 4,
                spaceBetween: 10,
            },
            1400: {
                slidesPerView: 5,
                spaceBetween: 30,
            }
        }
    });
    var best_seller_swiper = new Swiper(".best_seller_swiper", {
        slidesPerView: 2,
        spaceBetween: 5,
        pagination: {
            el: ".swiper-pagination",
            clickable: true,
        },
        navigation: {
            nextEl: ".swiper-button-next-best-seller",
            prevEl: ".swiper-button-prev-best-seller",
        },
        breakpoints: {
            640: {
                slidesPerView: 3,
                spaceBetween: 5,
            },
            768: {
                slidesPerView: 3,
                spaceBetween: 30,
            },
            1024: {
                slidesPerView: 4,
                spaceBetween: 10,
            },
            1400: {
                slidesPerView: 5,
                spaceBetween: 30,
            }
        }
    });
    var newest_seller = new Swiper(".newest_swiper", {
        slidesPerView: 2,
        spaceBetween: 5,
        pagination: {
            el: ".swiper-pagination",
            clickable: true,
        },
        navigation: {
            nextEl: ".swiper-button-next-newest",
            prevEl: ".swiper-button-prev-newest",
        },
        breakpoints: {
            640: {
                slidesPerView: 3,
                spaceBetween: 5,
            },
            768: {
                slidesPerView: 3,
                spaceBetween: 30,
            },
            1024: {
                slidesPerView: 4,
                spaceBetween: 10,
            },
            1400: {
                slidesPerView: 5,
                spaceBetween: 30,
            }
        }
    });
</script>
{% endblock %}

templates/shop/product_detail.html
{% extends 'parent/base.html' %}
{% load static %}
{% load humanize %}
{% load jformat %}
{% block title %}  Product name {% endblock %}
{% block head %}
    <link rel="stylesheet" href="{% static 'style/detail.css' %}">
{% endblock %}
{% block body %}
    <!-- historical navbar -->
     <div class="container">
        <div class="product-detail">
            <div class="wrapper detail">
                <div class="detail-image">
                    <img src="{{ product.images.first.image_file.url }}" alt="product">
                </div>
                <div class="product-wrapper">
                    <h1 class="product-detail-name">{{ product.name }}</h1>
                    <div class="features">
                        <p class="features-title">ویژگی های محصول</p>
                        <ul>
                            {% for feature in product.features.all %}
                            <li> {{ feature.name }}  {{ feature.value }}</li>
                            {% endfor %}
                        </ul>
                    </div>
                </div>
            </div>
            <div class="product-info">
                <div class="product-inventory">
                    <p class="inventory"> موجودی : {{ product.inventory }} </p>
                </div>
                {% if product.inventory %}
                <div class="product-price">
                    <p>قیمت محصول</p>
                    {% if product.off_percent != 0 %}
                    <p class="price off">{{ product.price | intcomma }} تومان</p>
                    <p class="off-price">{{ product.new_price | intcomma }} تومان</p>
                    {% else %}
                    <p class="price">{{ product.price | intcomma }} تومان</p>
                    {% endif %}
                </div>
                <div class="add-cart">
                    <button class="add-cart-btn">افزودن به سبد خرید</button>
                </div>
                {% else %}
                <div class="product-price">
                    ناموجود
                </div>
                <div class="add-cart">
                    <button class="disactive">افزودن به سبد خرید</button>
                </div>
                {% endif %}
            </div>
        </div>
        <div class="wrapper">
            <h2 class="description-title">توضیحات</h2>
            <p class="decription">{{ product.description }}</p>
        </div>
        <div class="wrapper">
            <h2 class="comments-title">نظرات</h2>
            <form method="post" class="comment-form">
                {% csrf_token %}
                <p class="new-comment">ایجاد نظر جدید</p>
                <input type="hidden" name="parent" value="None" class="parent-input">
                <textarea name="comment" class="comment-input" rows="10"></textarea>
                <input type="submit" value="ثبت نظر" class="comment-submit-btn">
            </form>
            <div class="comments">
                {% if comments %}
                {% for comment in comments %}
                <div class="comment" data-parent="{{comment.id}}">
                    <div class="comment-header">
                        {% if comment.user.has_full_name %}
                        <div class="comment-user"> {{ comment.user.get_full_name }} <span class="date">( {{comment.created | jformat:"%Y/%m/%d" }} )</span>  </div>
                        {% else %}
                        <div class="comment-user"> کاربر ناشناس <span class="date">( {{comment.created | jformat:"%Y/%m/%d" }} )</span> </div>
                        {% endif %}
                        <p class="reply-btn">پاسخ</p>
                    </div>
                    <div class="comment-body" id="comment_{{comment.id}}">{{ comment.content }}</div>
                    {% if comment.replies.all %}
                    {% for reply in comment.replies.all %}
                    {% if reply.active %}
                    <div class="reply">
                        <div class="comment-header">
                            {% if reply.user.has_full_name %}
                            <div class="comment-user"> {{ reply.user.get_full_name }} ( {{reply.created | jformat:"%Y/%m/%d" }} ) </div>
                            {% else %}
                            <div class="comment-user"> کاربر ناشناس ( {{reply.created | jformat:"%Y/%m/%d" }} ) </div>
                            {% endif %}
                        </div>
                        <div class="comment-body">{{ reply.content }}</div>
                    </div>
                    {% endif %}
                    {% endfor %}
                    {% endif %}
                </div>
                {% endfor %}
                {% else %}
                <div class="comment-empty">
                    هنوز هیچ نظری ثبت نشده است.
                </div>
                {% endif %}
            </div>
        </div>
     </div>
     <div class="modal">
         <div class="success-modal">
            <span class="close-btn">x</span>
            <p class="message"></p>
         </div>
         <div class="unsuccess-modal">
            <span class="close-btn">x</span>
            <p class="message"></p>
         </div>
     </div>

     <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.7.1/jquery.min.js" integrity="sha512-v2CJ7UaYy4JwqLDIrZUI/4hqeoQieOmAZNXBeQyjo21dadnwR+8ZaIJVT8EE2iyI61OV8e6M8PP2/4hpQINQ/g==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
     <script>

        function sendFormAsAjax(event){
            $(document).ready(function() {
                let data = $(event.target).serialize()
                $.ajax({
                    type: 'POST',
                    url: "{% url 'shop:add_comment' product.id %}",
                    data: data,
                    success: function(response) {
                        let success = response.success;
                        let message = response.message;
                        if (success) {
                            $('.success-modal .message').empty()
                            $('.success-modal .message').text(message)
                            $('.success-modal').css('display', 'block')
                            $('.comment-input').val('')
                        } else {
                            $('.unsuccess-modal .message').empty()
                            $('.unsuccess-modal .message').text(message)
                            $('.unsuccess-modal').css('display', 'block')
                        }
                    }
                })
            })
        }

         function sendReplyForm(event){
            event.preventDefault()
            sendFormAsAjax(event)
            event.target.style.display = 'none'
         }

        $(document).ready(function() {
            $(".add-cart-btn").click(function(){
                $.ajax({
                    type: "POST",
                    url: "{% url 'cart:update_cart' %}",
                    data: {'csrfmiddlewaretoken': '{{ csrf_token }}', 'action': 'add', 'product_id': '{{ product.id }}' },
                    success: function(data) {
                        $(".cart-total-price").text(data.cart_total_price + " تومان ");
                        $(".cart-total-count").text(data.cart_count);
                    }
                });
            });
            
            $('.comment-form').on('submit', function(e) {
                e.preventDefault()
                sendFormAsAjax(e)
            })
        
            $('.close-btn').click(function () {
                $('.success-modal').css('display', 'none');
                $('.unsuccess-modal').css('display', 'none');
            })

            $('.reply-btn').click(function() {
                let parent_id = $(this).closest('.comment').data('parent')
                let replyFrom = `<form method="post" class="comment-form" onsubmit="sendReplyForm(event)">
                        {% csrf_token %}
                        <p class="new-comment"> پاسخ به نظر </p>
                        <input type="hidden" name="parent" value="${parent_id}" class="parent-input">
                        <textarea name="comment" class="comment-input" rows="2"></textarea>
                        <input type="submit" value="ثبت پاسخ" class="comment-submit-btn">
                        <button class="comment-cancel-submit-btn">لغو پاسخ </button>
                    </form>`
                $(replyFrom).insertAfter('#comment_' + parent_id)
            })

            $('.comment-cancel-submit-btn').click(function() {
                $(this).closest('comment-form').remove()
            })
        });
     </script>
{% endblock %}

templates/shop/product_list_ajax.html
{% load humanize %}
<div class="all-products-list">
    {% if products %}
    {% for product in products %}
    <div class="product">
        <a href="{% url 'shop:product_detail' product.id product.slug %}">
            <img class="product-image" src="{{ product.images.first.image_file.url }}" alt="product">
        </a>
        <a href="{% url 'shop:product_detail' product.id product.slug %}">
            <p class="product-caption">{{ product.name }}</p>
        </a>
        {% if product.inventory %}
            <div class="product-price">
                {% if product.off_percent != 0 %}
                <span class="price off"> {{ product.price | intcomma }} تومان</span>
                <span class="price-off">{{ product.new_price | intcomma }} تومان</span>
                {% else %}
                <span class="price"> {{ product.price | intcomma }} تومان</span>
                {% endif %}
            </div>
            {% if product.off_percent != 0 %}
            <span class="off-percent">%{{ product.off_percent }}</span>
            {% endif %}
        {% else %}
        <p class="non-existent">
            ناموجود
        </p>
        {% endif %}
    </div>
    {% endfor %}
    {% else %}
    <div class='products-empty'>
        <p> هیچ محصولی یافت نشد </p>
    </div>
    {% endif %}
</div>
{% include 'partials/pagination.html' %}