bytemarket/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('shop.urls', namespace='shop')),
    path('account/', include('account.urls', namespace='account')),
    path('cart/', include('cart.urls', namespace='cart')),
    path('order/', include('order.urls', namespace='order')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

cart/urls.py
from django.urls import path
from . import views

app_name = 'cart'

urlpatterns = [
    path('', views.index, name='cart'),
    path('update-cart/', views.update_cart, name='update_cart'),
    path('delete/', views.delete_item, name='delete_item'),
    path('clear/', views.clear_cart, name='clear_cart'),
]

order/urls.py
from django.urls import path
from . import views

app_name = 'order'

urlpatterns = [
    path('order-create/', views.order_create, name='order_create'),
    path('confirm-order/<int:order_id>/', views.confirm_order, name='confirm_order'),
    path('order-edit/<int:order_id>/', views.order_edit, name='order_edit'),
    path('order/detail/<order_id>/', views.order_detail, name='order_detail'),
    path('get/cities/', views.get_cities, name='get_cities'),
]

shop/urls.py
from django.urls import path
from . import views

app_name = 'shop'

urlpatterns = [
    path('', views.index, name='index'),
    path('products/', views.products_list, name='products_list_all'),
    path('products/category/<category_slug>/', views.products_list, name='products_list'),
    path('product/<id>/<slug>/', views.product_detail, name='product_detail'),
    path('products/search', views.product_search, name='product_search'),
    path('product/add/comment/<product_id>', views.add_comment, name='add_comment'),
    path('products/<portion>/', views.products_portion, name='products_portion'),
]

order/models.py
from django.db import models
from shop.models import Product
from account.models import User


class Order(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='orders')
    phone = models.CharField(max_length=11)
    first_name = models.CharField(max_length=255)
    last_name = models.CharField(max_length=255)
    postal_code = models.CharField(max_length=255)
    address = models.TextField()
    province = models.ForeignKey("Province", on_delete=models.CASCADE, related_name='province_orders', null=True, blank=True)
    city = models.ForeignKey("City", on_delete=models.CASCADE, related_name='city_orders', null=True, blank=True)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    is_paid = models.BooleanField(default=False)
    
    def final_price(self):
        return sum([item.price * item.quantity for item in self.items.all()])

    def __str__(self):
        return f"order{self.id}: {self.phone}"


class OrderItem(models.Model):
    order = models.ForeignKey(Order, on_delete=models.CASCADE, related_name='items')
    product = models.ForeignKey(Product, on_delete=models.CASCADE, related_name='order_items')
    quantity = models.PositiveIntegerField()
    price = models.PositiveIntegerField()
    weight = models.PositiveIntegerField()

    def __str__(self):
        return f"order_item: {self.product.name}"


class Province(models.Model):
    name = models.CharField(max_length=50)
    
    def __str__(self):
        return self.name


class City(models.Model):
    name = models.CharField(max_length=50)
    province = models.ForeignKey(Province, on_delete=models.CASCADE, related_name='cities')
    
    def __str__(self):
        return self.name

order/forms.py
from django import forms
from .models import Order


class OrderCreateForm(forms.ModelForm):
    class Meta:
        model = Order
        fields = ['phone', 'first_name', 'last_name', 'postal_code', 'address', 'province', 'city']

    def clean_phone(self):
        phone = self.cleaned_data['phone']
        
        if len(phone) != 11:
            raise forms.ValidationError('شماره تلفن نامعتبر است.')
        
        if not phone.isdigit():
            raise forms.ValidationError('شماره تلفن فقط می تواند شامل عدد باشد.')
        
        if not phone.startswith('09'):
            raise forms.ValidationError('شماره تلفن باید با 09 شروع شود.')
        
        return phone
    
    def clean_postal_code(self):
        postal_code = self.cleaned_data['postal_code']
        
        if not postal_code.isdigit():
            raise forms.ValidationError('کد پستی فقط شامل عدد می تواند باشد.')
        
        return postal_code
    
    def clean_province(self):
        province = self.cleaned_data['province']
        
        if not province:
            raise forms.ValidationError('این فیلد نمی تواند خالی باشد')
        return province
    
    def clean_city(self):
        city = self.cleaned_data['city']
        
        if not city:
            raise forms.ValidationError('این فیلد نمی تواند خالی باشد')
        return city

order/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .forms import OrderCreateForm
from cart.cart import Cart
from .models import *


def order_create(request):
    """Create an order from user cart"""
    user = request.user
    # Check that the user is logged in, if not redirect user to login page
    if user.is_authenticated:
        cart = Cart(request)
        if request.method == 'POST':
            form = OrderCreateForm(request.POST)
            
            # Get province and city names from request
            province_id = request.POST.get('province')
            city_id = request.POST.get('city')
            if form.is_valid():
                order = form.save(commit=False)
                order.user = user
                order.province = Province.objects.get(id=province_id)
                order.city = City.objects.get(id=city_id)
                order.save()
                
                # Create order item from cart products
                for item in cart:
                    OrderItem.objects.create(order=order, 
                                             product=item['product'], 
                                             quantity=item['quantity'],
                                             price=item['price'], 
                                             weight=item['weight'])
                return redirect('order:confirm_order', order_id=order.id)
        else:
            form = OrderCreateForm()
        context = {
            'cart': cart,
            'user': user,
            'form': form,
            'provinces': Province.objects.all(),
        }
        return render(request, 'order/order_create.html', context)
    else:
        # Add the current url to the session to redirect to it after login
        request.session['next_url'] = '/order/order-create/'
        return redirect('account:verify_phone')


def confirm_order(request, order_id):
    cart = Cart(request)
    order = Order.objects.get(id=order_id)
    context = {
        'cart': cart,
        'order': order,
    }
    return render(request, 'order/confirm_order.html', context)


def order_edit(request, order_id):
    order = Order.objects.get(id=order_id)
    if request.method == 'POST':
        form = OrderCreateForm(request.POST, instance=order)
        province_id = request.POST.get('province')
        city_id = request.POST.get('city')
        if form.is_valid():
            order = form.save(commit=False)
            order.province = Province.objects.get(id=province_id)
            order.city = City.objects.get(id=city_id)
            order.save()
            return redirect('order:confirm_order', order_id=order_id)
    else:
        form = OrderCreateForm(instance=order)
    context = {
        'form': form,
        'provinces': Province.objects.all()
    }
    return render(request, 'order/order_edit.html', context)


def order_detail(request, order_id):
    order = get_object_or_404(Order, id=order_id)
    return render(request, 'order/order_detail.html', {'order': order})


def get_cities(request):
    """Return cities of a specified province"""
    province = request.GET.get('province')
    if province:
        cities = Province.objects.get(id=province).cities.all()
        return render(request, 'order/city_ajax.html', {'cities': cities})

templates/order/city_ajax.html
<option value="None">شهر خود را انتخاب کنید.</option>
{% for city in cities %}
<option value="{{city.id}}">{{city.name}}</option>
{% endfor %}

templates/order/confirm_order.html
{% extends 'parent/base.html' %}
{% load static %}
{% load humanize %}
{% block head %}
    <link rel="stylesheet" href="{% static 'style/order.css' %}">
{% endblock %}
{% block title %} تایید سفارش و پرداخت {% endblock %}
{% block body %}
    <div class="container">
        <div class="user-info">
            <h2 class="user-info-title">اطلاعات شما </h2>
            <p>نام : {{ order.first_name }}</p>
            <p>نام خانوادگی : {{ order.last_name }}</p>
            <p>شماره : {{ order.phone }}</p>
            <p>آدرس : {{ order.address }}</p>
            <p>کد پستی : {{ order.postal_code }}</p>
            <p>استان  : {{ order.province }}</p>
            <p>شهر  : {{ order.city }}</p>
            <a class="change-info-btn" href="{% url 'order:order_edit' order.id %}">ویرایش اطلاعات</a>
        </div>
        <div class="user-order">
            <h2 class="user-order-title">سفارش شما</h2>
            <table id="keywords" cellspacing="0" cellpadding="0" dir="rtl">
                <thead>
                    <tr>
                    <th><span>ردیف</span></th>
                    <th><span>نام محصول</span></th>
                    <th><span>تعداد</span></th>
                    <th><span>قیمت (تومان)</span></th>
                    </tr>
                </thead>
                <tbody>
                {% for item in cart %}
                    <tr>
                    <td>{{forloop.counter}}</td>
                    <td>{{ item.product.name }}</td>
                    <td>{{ item.quantity }}</td>
                    <td>{{ item.price | intcomma }}</td>
                    </tr>
                {% endfor %}
                </tbody>
            </table>
            <div class="user-order-products">
                {% for item in cart %}
                <div class="user-order-product">
                    <p class="user-order-product-title">{{ item.product.name }}</p>
                    <div class="user-order-product-detail">
                        <p class="user-order-product-quantity">تعداد : {{ item.quantity }}</p>
                        <p class="user-order-product-price">قیمت : {{ item.price | intcomma }}</p>
                    </div>
                </div>
                {% endfor %}
            </div>
            <div class="result">
            <p class="post-price">هزینه پست : {{ cart.post_price | intcomma }} تومان</p>
            <p class="payment-price">مبلغ کل : {{ cart.final_total_price | intcomma }} تومان</p>
            <div class="payment-btns">
                <a href="#" class="payment-btn">پرداخت</a>
            </div>
        </div>
        </div>

    </div>
{% endblock %}

templates/order/order_create.html
{% extends 'parent/base.html' %}
{% load static %}
{% load humanize %}
{% load order_tags %}
{% block head %}
    <link rel="stylesheet" href="{% static 'style/order.css' %}">
{% endblock %}
{% block title %} ثبت سفارش {% endblock %}
{% block body %}
    <div class="container">
        <div class="user-order">
            <h2 class="user-order-title">سفارش شما</h2>
            <table id="keywords" cellspacing="0" cellpadding="0" dir="rtl">
                <thead>
                    <tr>
                    <th><span>ردیف</span></th>
                    <th><span>نام محصول</span></th>
                    <th><span>تعداد</span></th>
                    <th><span>قیمت (تومان)</span></th>
                    </tr>
                </thead>
                <tbody>
                {% for item in cart %}
                    <tr>
                    <td>{{forloop.counter}}</td>
                    <td>{{ item.product.name }}</td>
                    <td>{{ item.quantity }}</td>
                    <td>{{ item.price | intcomma }}</td>
                    </tr>
                {% endfor %}
                </tbody>
            </table>
            <div class="user-order-products">
                {% for item in cart %}
                <div class="user-order-product">
                    <p class="user-order-product-title">{{ item.product.name }}</p>
                    <div class="user-order-product-detail">
                        <p class="user-order-product-quantity">تعداد : {{ item.quantity }}</p>
                        <p class="user-order-product-price">قیمت : {{ item.price | intcomma }}</p>
                    </div>
                </div>
                {% endfor %}
            </div>
        </div>
        <div class="user-info">
            <h2 class="user-info-title">اطلاعات شخصی </h2>
            <form action="#" method="post">
                {% csrf_token %}
                <div class="info-wrapper">
                    <div class="input-wrapper">
                        <label for="first_name">نام:</label>
                        <input type="text" id="first_name" name="first_name" maxlength="255" required {% if form.first_name.value %} value="{{ form.first_name.value }}" {% endif %}>
                        {% for error in form.first_name.errors %}
                            <span class="input-error">{{ error }}</span>
                        {% endfor %}
                    </div>
                    <div class="input-wrapper">
                        <label for="last_name">نام خانوادگی:</label>
                        <input type="text" id="last_name" name="last_name" maxlength="255" required {% if form.last_name.value %} value="{{ form.last_name.value }}" {% endif %}>
                        {% for error in form.last_name.errors %}
                            <span class="input-error">{{ error }}</span>
                        {% endfor %}
                    </div>
                </div>
                <div class="info-wrapper">
                    <div class="input-wrapper">
                        <label for="postal_code">کد پستی:</label>
                        <input type="text" id="postal_code" name="postal_code" maxlength="11" required {% if form.postal_code.value %} value="{{ form.postal_code.value }}" {% endif %}>
                        {% for error in form.postal_code.errors %}
                            <span class="input-error">{{ error }}</span>
                        {% endfor %}
                    </div>
                    <div class="input-wrapper">
                        <label for="phone">تلفن همراه:</label>
                        <input type="text" id="phone" name="phone" maxlength="11" required {% if form.phone.value %} value="{{ form.phone.value }}" {% endif %}>
                        {% for error in form.phone.errors %}
                            <span class="input-error">{{ error }}</span>
                        {% endfor %}
                    </div>
                </div>
                <div class="info-wrapper">
                    <div class="input-wrapper">
                        <label for="province">استان :</label>
                        <select name="province" id="province" class="select">
                            <option value="">استان خود را انتخاب کنید:</option>
                            {% for province in provinces %}
                            <option value="{{province.id}}">{{province.name}}</option>
                            {% endfor %}
                        </select>
                    </div>
                    <div class="input-wrapper">
                        <label for="city">شهر :</label>
                        <select name="city" id="city" class="select">
                            <option value="">شهر خود را انتخاب کنید.</option>
                        </select>
                    </div>
                </div>
                <div class="info-wrapper">
                    <div class="input-wrapper">
                        <label for="address">آدرس:</label>
                        {% nospaces %}
                        <textarea name="address" id="address" rows="3" cols="10">
                            {% if form.address.value %}
                                {{ form.address.value }}
                            {% endif %}
                        </textarea>
                        {% endnospaces %}
                        {% for error in form.address.errors %}
                            <span class="input-error">{{ error }}</span>
                        {% endfor %}
                    </div>
                </div>
                <button class="submit-btn" type="submit">ثبت اطلاعات</button>
            </form>
        </div>
    </div>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.7.1/jquery.min.js" integrity="sha512-v2CJ7UaYy4JwqLDIrZUI/4hqeoQieOmAZNXBeQyjo21dadnwR+8ZaIJVT8EE2iyI61OV8e6M8PP2/4hpQINQ/g==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
    <script>
        $(document).ready(function(){
            $('#province').change(function(event){
                let province = $(this).val()
                $.ajax({
                    type: 'GET',
                    url: '{% url "order:get_cities" %}',
                    data: {'province':province},
                    dataType: 'html',
                    success: function(response){
                        $('#city').empty()
                        $('#city').append(response)
                    }
                })
            })
        })
    </script>
{% endblock %}

templates/order/order_detail.html
{% extends 'parent/base.html' %}
{% load static %}
{% load humanize %}
{% load jformat %}
{% block title %} جزئیات سفارش {% endblock %}
{% block head %} 
    <link rel="stylesheet" href="{% static 'style/order.css' %}">
{% endblock %}

{% block body %}
    <div class="container">
        <div class="wrapper">

            <!-- orders section -->
            <section class="order-detail">
                <div class="order-detail-header">
                    <h3 class="orders-title">سفارش {{ order.id }}</h3>
                    {% if order.is_paid %}
                    <p class="order-status"> وضعیت : <span class="gr">پرداخت شده</span></p>
                    {% else %}
                    <p class="order-status"> وضعیت : <span class="re">پرداخت نشده</span> </p>
                    {% endif %}
                    <p class="order-date">تاریخ : {{ order.created | jformat:"%Y/%m/%d" }}</p>
                </div>
                {% for item in order.items.all %}
                <div class="product-item">
                    <p class="row">{{ forloop.counter }}</p>
                    <a href="{% url 'shop:product_detail' item.product.id item.product.slug %}"><img src="{{ item.product.images.first.image_file.url }}" alt="{{ item.product.category }}" class="product-item-image"></a>
                    <div class="product-item-detail">
                        <a href="{% url 'shop:product_detail' item.product.id item.product.slug %}" class="product-item-name">{{ item.product.name }}</a>
                        <div class="detail-price">
                            <p class="item-product-price">قیمت : {{ item.price | intcomma }}</p>
                            <p class="item-product-quantity">تعداد : {{ item.quantity }}</p>
                        </div>
                    </div>
                </div>
                {% endfor %}

            </section>
        </div>
    </div>
{% endblock %}

templates/order/order_edit.html
{% extends 'parent/base.html' %}
{% load static %}
{% load order_tags %}
{% block head %}
    <link rel="stylesheet" href="{% static 'style/order.css' %}">
{% endblock %}
{% block title %}
    اطلاعات شخصی
{% endblock %}
{% block body %}
    <div class="container">
        <div class="user-info">
            <h2 class="user-info-title">اطلاعات شخصی </h2>

            <form method="post">
                {% csrf_token %}
                <div class="info-wrapper">
                    <div class="input-wrapper">
                        <label for="first_name">نام:</label>
                        <input type="text" id="first_name" name="first_name" maxlength="255" required {% if form.first_name.value %} value="{{ form.first_name.value }}" {% endif %}>
                        {% for error in form.first_name.errors %}
                            <span class="input-error">{{ error }}</span>
                        {% endfor %}
                    </div>
                    <div class="input-wrapper">
                        <label for="last_name">نام خانوادگی:</label>
                        <input type="text" id="last_name" name="last_name" maxlength="255" required {% if form.first_name.value %} value="{{ form.last_name.value }}" {% endif %}>
                        {% for error in form.last_name.errors %}
                            <span class="input-error">{{ error }}</span>
                        {% endfor %}
                    </div>
                </div>
                <div class="info-wrapper">
                    <div class="input-wrapper">
                        <label for="postal_code">کد پستی:</label>
                        <input type="text" id="postal_code" name="postal_code" maxlength="11" required {% if form.first_name.value %} value="{{ form.postal_code.value }}" {% endif %}>
                        {% for error in form.postal_code.errors %}
                            <span class="input-error">{{ error }}</span>
                        {% endfor %}
                    </div>
                    <div class="input-wrapper">
                        <label for="phone">تلفن همراه:</label>
                        <input type="text" id="phone" name="phone" maxlength="255" required {% if form.first_name.value %} value="{{ form.phone.value }}" {% endif %}>
                        {% for error in form.phone.errors %}
                            <span class="input-error">{{ error }}</span>
                        {% endfor %}
                    </div>
                </div>
                <div class="info-wrapper">
                    <div class="input-wrapper">
                        <label for="province">استان :</label>
                        <select name="province" id="province" class="select">
                            <option value="">استان خود را انتخاب کنید:</option>
                            {% for province in provinces %}
                            <option value="{{province.id}}">{{province.name}}</option>
                            {% endfor %}
                        </select>
                        {% for error in form.province.errors %}
                            <span class="input-error">{{ error }}</span>
                        {% endfor %}
                    </div>
                    <div class="input-wrapper">
                        <label for="city">شهر :</label>
                        <select name="city" id="city" class="select">
                            <option value="">شهر خود را انتخاب کنید.</option>
                        </select>
                        {% for error in form.city.errors %}
                            <span class="input-error">{{ error }}</span>
                        {% endfor %}
                    </div>
                    
                </div>
                <div class="info-wrapper">
                    <div class="input-wrapper">
                        <label for="address">آدرس:</label>
                        {% nospaces %}
                        <textarea name="address" id="address" rows="3" cols="10">
                            {% if form.address.value %}
                                {{ form.address.value }}
                            {% endif %}
                        </textarea>
                        {% endnospaces %}
                        {% for error in form.address.errors %}
                            <span class="input-error">{{ error }}</span>
                        {% endfor %}
                    </div>
                </div>
                <button class="submit-btn" type="submit">ثبت اطلاعات</button>
            </form>
        </div>
    </div>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.7.1/jquery.min.js" integrity="sha512-v2CJ7UaYy4JwqLDIrZUI/4hqeoQieOmAZNXBeQyjo21dadnwR+8ZaIJVT8EE2iyI61OV8e6M8PP2/4hpQINQ/g==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
    <script>
        $(document).ready(function(){
            $('#province').change(function(event){
                let province = $(this).val()
                $.ajax({
                    type: 'GET',
                    url: '{% url "order:get_cities" %}',
                    data: {'province':province},
                    dataType: 'html',
                    success: function(response){
                        $('#city').empty()
                        $('#city').append(response)
                    }
                })
            })
        })
    </script>
{% endblock %}